version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run: |
         echo "$DOCKER_PASSWORD" | docker login quay.io --username $DOCKER_USER --password-stdin
         #echo "$DOCKER_PASSWORD" | script -c bash -c "docker login quay.io --username $DOCKER_USER --password-stdin"
      - run:
          name: Build
          command: make
          no_output_timeout: 240m
