version: 2
jobs:
  image-build:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run: |
         make login
      - run:
          name: Build
          command: make image/build
          no_output_timeout: 240m
      - run:
          name: Push
          command: make image/push
  bpftrace:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run: |
         make login
      - run:
          name: Pull
          command: make image/pull
      - run:
          name: Build
          command: make bpftrace
      - store_artifacts:
          path: bpftrace

workflows:
  version: 2
  build-all:
    jobs:
      - image-build:
          filters:
            branches:
              only: /image-build/
      - bpftrace
